[package]
name = "dryice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-compression = "0.4.21"
bio-seq = { version = "0.14.2", features = ["serde", "translation", "extra_codecs"] }
bitcode = "0.6.6"
color-eyre = "0.6.3"
fern = "0.7.1"
log = "0.4.26"
noodles = { version = "0.95.0", features = ["bam", "bcf", "bgzf", "core", "async", "cram", "csi", "sam", "fasta", "fastq", "tabix", "vcf", "htsget", "refget"] }
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive", "serde_derive"] }
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
zstd = "0.13.3"

[dev-dependencies]
assay = "0.1.1"
biotest = { version = "0.2.0", features = ["fasta", "fastq", "quality", "sequence", "vcf"] }
pretty_assertions = "1.4.1"
sccache = "0.10.0"
