from typing import Iterator, Optional

class WriterBuilder:
    """Builder for configuring a DryIce writer."""

    def __init__(self) -> None: ...
    def two_bit_exact(self) -> WriterBuilder: ...
    def two_bit_lossy_n(self) -> WriterBuilder: ...
    def binned_quality(self) -> WriterBuilder: ...
    def split_names(self) -> WriterBuilder: ...
    def bytes8_key(self) -> WriterBuilder: ...
    def target_block_records(self, n: int) -> WriterBuilder: ...
    def build(self) -> Writer: ...

class Writer:
    """A dryice file writer."""

    @staticmethod
    def builder() -> WriterBuilder: ...
    def write_record(self, name: bytes, sequence: bytes, quality: bytes) -> None: ...
    def write_record_with_key(
        self, name: bytes, sequence: bytes, quality: bytes, key: bytes
    ) -> None: ...
    def finish(self) -> bytes: ...

class Record:
    """A decoded sequencing record."""

    name: Optional[bytes]
    sequence: Optional[bytes]
    quality: Optional[bytes]
    key: Optional[bytes]

class ReaderBuilder:
    """Builder for configuring a DryIce reader."""

    def __init__(self) -> None: ...
    def two_bit_exact(self) -> ReaderBuilder: ...
    def two_bit_lossy_n(self) -> ReaderBuilder: ...
    def binned_quality(self) -> ReaderBuilder: ...
    def split_names(self) -> ReaderBuilder: ...
    def bytes8_key(self) -> ReaderBuilder: ...
    def build(self, data: bytes) -> Reader: ...

class Reader:
    """A dryice file reader."""

    @staticmethod
    def builder() -> ReaderBuilder: ...
    @staticmethod
    def open(data: bytes) -> Reader: ...
    def __iter__(self) -> Iterator[Record]: ...
    def __next__(self) -> Record: ...

def open_projected(
    data: bytes,
    projection: str,
    sequence_codec: str = "raw",
    quality_codec: str = "raw",
    name_codec: str = "raw",
    record_key: str = "none",
) -> Reader: ...
